name: CD to publish Hugo site to S3
on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - archetypes/**
      - layouts/**
      - themes/**
      - content/**
      - static/**
      - hugo.toml
      - Makefile
      - .github/workflows/cd-blog.yml
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_DEFAULT_REGION: "${{ secrets.AWS_DEFAULT_REGION }}"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    steps:
      - uses: actions/cache@v4
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
       
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
           make build
        
      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: |
           make publish